# Generated by Django 5.1.1 on 2024-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('post_status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('job_type', models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('remote', 'Remote')], max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('post_status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
