# Generated by Django 5.1.1 on 2024-10-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='post_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='post_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='Active', max_length=100),
        ),
    ]
